-- ============================================================
-- MIGRATION: BDM handoff loop — the database half of BDM.md Step 3
-- Written 2026-09-15. Read BDM.md (repo root) first.
--
-- RUN: paste this whole file into the Supabase SQL Editor and press Run.
-- Wrapped in BEGIN/COMMIT — it applies completely or not at all. Safe to
-- re-run. Needs Schema/migration_bdm_role.sql to have run first (it reads
-- leads.bdm_employee_id).
--
-- RUN IT BEFORE redeploying the Edge Function (the function writes the new
-- 'bdm_pool_nudge' kind, which STEP 1 is what allows). Order vs the app
-- deploy doesn't matter: nothing here adds a column, and every function keeps
-- its exact signature and result shape.
--
--   STEP 1  notifications.kind accepts 'bdm_pool_nudge' (the owner's 24-hour
--           push for a pool lead nobody has assigned yet — owner's ruling:
--           a push, not a red label)
--   STEP 2  every dashboard RPC leaves BDM pool leads out of its figures
--
-- STEP 2 — WHY. Owner's ruling (BDM.md Step 2, answer 3): a lead a BDM sends
-- to the owner is NOT part of the company pipeline until the owner assigns
-- it. The pool card on the owner's Today is the only place it shows. The app
-- side filters its own lead queries (src/lib/poolLeads.js); these eight
-- functions count leads in Postgres, so they need the same rule here.
--
-- The predicate, identical in all eight — "a pool lead" is exactly
-- `owner_employee_id IS NULL AND bdm_employee_id IS NOT NULL`:
--
--   AND (l.owner_employee_id IS NOT NULL OR l.bdm_employee_id IS NULL
--        OR (SELECT current_employee_role()) = 'business_development_manager')
--
--   * An ownerless lead NOT from a BDM is not a pool lead and keeps counting
--     as "Unassigned", exactly as before (there were 0 of those on
--     2026-09-15, of 1,265 leads).
--   * The BDM who brought a pool lead in still counts it — it IS their
--     pipeline, and BDM.md Step 5 reads these RPCs under the BDM's own RLS.
--     Under RLS a BDM can only ever see their own pool leads anyway, and no
--     other role can see a pool lead at all, so the role test only ever
--     changes the answer for the owner.
--   * (SELECT …) is evaluated once per statement, not per row (the CLAUDE.md
--     RLS-performance pattern). For the owner the first test is true for
--     almost every row, so the rest never runs.
--
-- Each function below is reproduced VERBATIM from its latest copy with only
-- the three predicate lines (and their comment) added — generated by script,
-- not retyped, and checked to have changed nothing else:
--   leads_on_hold_detail, leads_completeness_detail,
--   leads_followup_gap_detail, leads_workload_by_owner,
--   leads_open_deal_ranking, dashboard_snapshot_metrics
--       ← migration_time_independent_dashboard_metrics.sql
--   leads_category_breakdown ← migration_leads_category_breakdown_rpc.sql
--       (its WHERE had no parentheses around the OR; now it does, which is
--       the same condition)
--   leads_needing_attention  ← migration_stale_7day_tile.sql (the 8-argument
--       version; CREATE OR REPLACE on the same signature, so no DROP needed)
--
-- ⚠️ LAYERING: re-running any of those three older files after this one
-- silently puts pool leads back into the owner's figures. Re-run this file
-- afterwards. STEP 1 likewise supersedes migration_bdm_role.sql STEP 10.
-- ============================================================

BEGIN;


-- ------------------------------------------------------------
-- STEP 1: notifications.kind
-- ------------------------------------------------------------
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_kind_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_kind_check
  CHECK (kind IN ('lead_assigned', 'lixil_lead_created',
                  'bdm_pool_lead', 'bdm_pool_nudge',
                  'bdm_lead_assigned', 'bdm_lead_won', 'bdm_lead_lost'));


-- ------------------------------------------------------------
-- STEP 2: dashboard RPCs exclude pool leads (see header)
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION leads_on_hold_detail(
  p_owner_ids         integer[] DEFAULT NULL,
  p_now               timestamptz DEFAULT NULL,
  p_tz_offset_minutes integer     DEFAULT NULL
)
RETURNS TABLE (
  lead_id         integer,
  party           text,
  owner_id        integer,
  owner_name      text,
  value           numeric,
  on_hold_reason  text,
  on_hold_since   timestamp,
  days_on_hold    integer,
  resume_date     date
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  WITH scoped AS (
    SELECT
      l.id,
      l.owner_employee_id,
      l.quote_value,
      l.on_hold_reason,
      l.next_followup_date,
      l.created_at,
      COALESCE(p.name, s.nickname, s.locality, '(no party)') AS party_label,
      COALESCE(e.name, 'Unassigned')                          AS owner_label,
      (SELECT sh.changed_at FROM stage_history sh
        WHERE sh.lead_id = l.id AND sh.stage = 'on_hold'
        ORDER BY sh.changed_at DESC LIMIT 1)                   AS hold_started_at
    FROM leads l
    LEFT JOIN parties   p ON p.id = l.party_id
    LEFT JOIN sites     s ON s.id = l.site_id
    LEFT JOIN employees e ON e.id = l.owner_employee_id
    WHERE COALESCE(l.current_stage, 'calling') = 'on_hold'
      AND (p_owner_ids IS NULL OR l.owner_employee_id = ANY (p_owner_ids))
      -- BDM pool leads stay out of every company figure until assigned
      -- (migration_bdm_handoff.sql) — except for the BDM who brought them in.
      AND (l.owner_employee_id IS NOT NULL OR l.bdm_employee_id IS NULL
           OR (SELECT current_employee_role()) = 'business_development_manager')
  ),
  timed AS (
    SELECT
      sc.*,
      COALESCE(sc.hold_started_at, sc.created_at) AS since_naive
    FROM scoped sc
  )
  SELECT
    t.id,
    t.party_label,
    t.owner_employee_id,
    t.owner_label,
    COALESCE(t.quote_value, 0),
    t.on_hold_reason,
    t.since_naive,
    CASE
      WHEN p_now IS NULL OR p_tz_offset_minutes IS NULL THEN NULL
      ELSE FLOOR(EXTRACT(EPOCH FROM (
        p_now - ((t.since_naive - make_interval(mins => p_tz_offset_minutes)) AT TIME ZONE 'UTC')
      )) / 86400)::int
    END,
    t.next_followup_date
  FROM timed t
  ORDER BY t.id
$$;


CREATE OR REPLACE FUNCTION leads_completeness_detail(p_owner_ids integer[] DEFAULT NULL)
RETURNS TABLE (
  lead_id           integer,
  party             text,
  owner_id          integer,
  owner_name        text,
  has_client_name   boolean,
  has_client_number boolean,
  has_address       boolean,
  has_pincode       boolean,
  has_site_stage    boolean,
  has_product       boolean,
  missing_fields    text[],
  completeness_pct  numeric
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  WITH scoped AS (
    SELECT
      l.id,
      l.owner_employee_id,
      l.site_id,
      l.product_id,
      l.party_id,
      COALESCE(dp.name, s.nickname, s.locality, '(no party)') AS party_label,
      COALESCE(e.name, 'Unassigned')                          AS owner_label,
      -- The CLIENT specifically (party_type = 'client'), not just "whoever
      -- is linked" — this is Rule per the brief, distinct from party_label
      -- above, which is the generic display-name fallback chain used
      -- everywhere else in this app (leads_needing_attention() etc.).
      dp_client.name    AS client_name_direct,
      dp_client.mobile  AS client_mobile_direct,
      site_owner.name   AS client_name_via_site,
      site_owner.mobile AS client_mobile_via_site,
      s.house_no,
      s.locality,
      s.pincode,
      s.site_stage
    FROM leads l
    LEFT JOIN parties dp        ON dp.id = l.party_id
    LEFT JOIN parties dp_client ON dp_client.id = l.party_id AND dp_client.party_type = 'client'
    LEFT JOIN sites   s         ON s.id = l.site_id
    LEFT JOIN employees e       ON e.id = l.owner_employee_id
    LEFT JOIN LATERAL (
      SELECT p2.name, p2.mobile
      FROM site_contacts sc
      JOIN parties p2 ON p2.id = sc.party_id
      WHERE sc.site_id = l.site_id AND sc.role = 'owner'
      ORDER BY sc.discovered_at ASC NULLS LAST, sc.id ASC
      LIMIT 1
    ) site_owner ON dp_client.id IS NULL AND l.site_id IS NOT NULL
    WHERE COALESCE(l.current_stage, 'calling') NOT IN ('won', 'lost')
      AND (p_owner_ids IS NULL OR l.owner_employee_id = ANY (p_owner_ids))
      -- BDM pool leads stay out of every company figure until assigned
      -- (migration_bdm_handoff.sql) — except for the BDM who brought them in.
      AND (l.owner_employee_id IS NOT NULL OR l.bdm_employee_id IS NULL
           OR (SELECT current_employee_role()) = 'business_development_manager')
  ),
  resolved AS (
    SELECT
      sc.*,
      COALESCE(sc.client_name_direct, sc.client_name_via_site)     AS client_name,
      COALESCE(sc.client_mobile_direct, sc.client_mobile_via_site) AS client_mobile
    FROM scoped sc
  ),
  flagged AS (
    SELECT
      r.*,
      (r.client_name IS NOT NULL AND r.client_name <> '')                                       AS f_client_name,
      (r.client_mobile IS NOT NULL AND r.client_mobile <> '')                                    AS f_client_number,
      (r.site_id IS NOT NULL AND (COALESCE(r.house_no, '') <> '' OR COALESCE(r.locality, '') <> '')) AS f_address,
      (r.site_id IS NOT NULL AND COALESCE(r.pincode, '') <> '')                                  AS f_pincode,
      (r.site_id IS NOT NULL AND COALESCE(r.site_stage, '') <> '')                               AS f_site_stage,
      (r.product_id IS NOT NULL)                                                                 AS f_product
    FROM resolved r
  )
  SELECT
    f.id,
    f.party_label,
    f.owner_employee_id,
    f.owner_label,
    f.f_client_name,
    f.f_client_number,
    f.f_address,
    f.f_pincode,
    f.f_site_stage,
    f.f_product,
    ARRAY_REMOVE(ARRAY[
      CASE WHEN NOT f.f_client_name   THEN 'client_name'   END,
      CASE WHEN NOT f.f_client_number THEN 'client_number' END,
      CASE WHEN NOT f.f_address       THEN 'address'       END,
      CASE WHEN NOT f.f_pincode       THEN 'pincode'       END,
      CASE WHEN NOT f.f_site_stage    THEN 'site_stage'    END,
      CASE WHEN NOT f.f_product       THEN 'product'       END
    ], NULL),
    ROUND(
      (f.f_client_name::int + f.f_client_number::int + f.f_address::int
       + f.f_pincode::int + f.f_site_stage::int + f.f_product::int) / 6.0 * 100,
      1
    )
  FROM flagged f
  ORDER BY f.id
$$;


CREATE OR REPLACE FUNCTION leads_followup_gap_detail(p_owner_ids integer[] DEFAULT NULL)
RETURNS TABLE (
  lead_id           integer,
  party             text,
  owner_id          integer,
  owner_name        text,
  stage             text,
  value             numeric,
  last_activity_at  timestamp
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  WITH last_activity AS (
    SELECT a.lead_id, MAX(a.created_at) AS last_at
    FROM activities a
    WHERE a.lead_id IS NOT NULL
    GROUP BY a.lead_id
  )
  SELECT
    l.id,
    COALESCE(p.name, s.nickname, s.locality, '(no party)'),
    l.owner_employee_id,
    COALESCE(e.name, 'Unassigned'),
    COALESCE(l.current_stage, 'calling'),
    -- Mirrors dealValueFor()'s open-lead branch (won/lost are already
    -- excluded by the WHERE clause below).
    COALESCE(l.quote_value, 0),
    la.last_at
  FROM leads l
  LEFT JOIN parties   p  ON p.id = l.party_id
  LEFT JOIN sites     s  ON s.id = l.site_id
  LEFT JOIN employees e  ON e.id = l.owner_employee_id
  LEFT JOIN last_activity la ON la.lead_id = l.id
  WHERE COALESCE(l.current_stage, 'calling') NOT IN ('won', 'lost', 'on_hold')
    AND l.next_followup_date IS NULL
    AND (p_owner_ids IS NULL OR l.owner_employee_id = ANY (p_owner_ids))
    -- BDM pool leads stay out of every company figure until assigned
    -- (migration_bdm_handoff.sql) — except for the BDM who brought them in.
    AND (l.owner_employee_id IS NOT NULL OR l.bdm_employee_id IS NULL
         OR (SELECT current_employee_role()) = 'business_development_manager')
  ORDER BY l.id
$$;


CREATE OR REPLACE FUNCTION leads_workload_by_owner(p_owner_ids integer[] DEFAULT NULL)
RETURNS TABLE (
  owner_id          integer,
  owner_name        text,
  open_lead_count   bigint,
  open_pipeline_value numeric
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT
    l.owner_employee_id                        AS owner_id,
    COALESCE(e.name, 'Unassigned')              AS owner_name,
    COUNT(*)                                    AS open_lead_count,
    -- Mirrors dealValueFor(): open leads (won/lost excluded by the WHERE
    -- below, on_hold intentionally included per the header note) value at
    -- their quote_value alone, coalesced to 0.
    SUM(COALESCE(l.quote_value, 0))             AS open_pipeline_value
  FROM leads l
  LEFT JOIN employees e ON e.id = l.owner_employee_id
  WHERE COALESCE(l.current_stage, 'calling') NOT IN ('won', 'lost')
    AND (p_owner_ids IS NULL OR l.owner_employee_id = ANY (p_owner_ids))
    -- BDM pool leads stay out of every company figure until assigned
    -- (migration_bdm_handoff.sql) — except for the BDM who brought them in.
    AND (l.owner_employee_id IS NOT NULL OR l.bdm_employee_id IS NULL
         OR (SELECT current_employee_role()) = 'business_development_manager')
  GROUP BY l.owner_employee_id, e.name
  ORDER BY open_lead_count DESC, owner_id
$$;


CREATE OR REPLACE FUNCTION leads_open_deal_ranking(p_owner_ids integer[] DEFAULT NULL)
RETURNS TABLE (
  lead_id     integer,
  party       text,
  owner_id    integer,
  owner_name  text,
  value       numeric
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT
    l.id,
    COALESCE(p.name, s.nickname, s.locality, '(no party)'),
    l.owner_employee_id,
    COALESCE(e.name, 'Unassigned'),
    COALESCE(l.quote_value, 0)
  FROM leads l
  LEFT JOIN parties   p ON p.id = l.party_id
  LEFT JOIN sites     s ON s.id = l.site_id
  LEFT JOIN employees e ON e.id = l.owner_employee_id
  WHERE COALESCE(l.current_stage, 'calling') NOT IN ('won', 'lost', 'on_hold')
    AND (p_owner_ids IS NULL OR l.owner_employee_id = ANY (p_owner_ids))
    -- BDM pool leads stay out of every company figure until assigned
    -- (migration_bdm_handoff.sql) — except for the BDM who brought them in.
    AND (l.owner_employee_id IS NOT NULL OR l.bdm_employee_id IS NULL
         OR (SELECT current_employee_role()) = 'business_development_manager')
  ORDER BY COALESCE(l.quote_value, 0) DESC, l.id
$$;


CREATE OR REPLACE FUNCTION dashboard_snapshot_metrics(
  p_owner_ids         integer[]   DEFAULT NULL,
  p_now               timestamptz DEFAULT NULL,
  p_tz_offset_minutes integer     DEFAULT NULL,
  p_top_fraction      numeric     DEFAULT 0.10
)
RETURNS TABLE (
  -- On-hold (metric #3 headline; also folds into metric #1's on-hold figure)
  on_hold_count               bigint,
  on_hold_value               numeric,
  on_hold_avg_days            numeric,

  -- Lead data completeness (metric #4)
  completeness_lead_count           bigint,
  completeness_pct                  numeric,
  completeness_client_name_pct      numeric,
  completeness_client_number_pct    numeric,
  completeness_address_pct          numeric,
  completeness_pincode_pct          numeric,
  completeness_site_stage_pct       numeric,
  completeness_product_pct          numeric,

  -- Follow-up coverage gap (metric #5)
  followup_gap_count         bigint,
  followup_gap_denominator   bigint,
  followup_gap_pct           numeric,

  -- Team workload balance (metric #6) — scalars only; full breakdown is
  -- leads_workload_by_owner(), fetched lazily by the drill-down.
  workload_employee_count    bigint,
  workload_busiest_owner_id  integer,
  workload_busiest_name      text,
  workload_busiest_count     bigint,
  workload_busiest_value     numeric,
  workload_lightest_owner_id integer,
  workload_lightest_name     text,
  workload_lightest_count    bigint,
  workload_lightest_value    numeric,

  -- Pipeline concentration (metric #7) — scalar only; full ranked list is
  -- leads_open_deal_ranking(), fetched lazily by the drill-down.
  concentration_pct               numeric,
  concentration_top_lead_count    integer,
  concentration_total_lead_count  bigint,
  concentration_total_value       numeric
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  WITH base AS (
    -- ONE scan of leads, carrying every join every metric below needs.
    -- Filtering to NOT IN ('won','lost') here is a real optimization, not
    -- just tidiness — every one of the six metrics only ever cares about
    -- open leads, so this cuts the row count before the expensive per-row
    -- RLS evaluation has to run on the excluded rows too (the planner is
    -- free to evaluate cheap conditions before expensive ones, and a bare
    -- column comparison is far cheaper than the coordinator/manager RLS
    -- branches).
    SELECT
      l.id,
      l.owner_employee_id,
      l.site_id,
      l.product_id,
      l.next_followup_date,
      COALESCE(l.quote_value, 0)                                  AS value,
      COALESCE(l.current_stage, 'calling') = 'on_hold'            AS is_on_hold,
      COALESCE(e.name, 'Unassigned')                              AS owner_label,
      dp_client.name    AS client_name_direct,
      dp_client.mobile  AS client_mobile_direct,
      site_owner.name   AS client_name_via_site,
      site_owner.mobile AS client_mobile_via_site,
      s.house_no, s.locality, s.pincode, s.site_stage,
      -- Only ever evaluated for an on-hold row — CASE short-circuits the
      -- untaken branch, so the ~85% of open leads that are active never
      -- pay for this correlated stage_history lookup at all.
      CASE WHEN COALESCE(l.current_stage, 'calling') = 'on_hold' THEN (
        SELECT sh.changed_at FROM stage_history sh
         WHERE sh.lead_id = l.id AND sh.stage = 'on_hold'
         ORDER BY sh.changed_at DESC LIMIT 1
      ) END AS hold_started_at,
      l.created_at
    FROM leads l
    LEFT JOIN employees e       ON e.id = l.owner_employee_id
    LEFT JOIN sites     s       ON s.id = l.site_id
    LEFT JOIN parties   dp_client ON dp_client.id = l.party_id AND dp_client.party_type = 'client'
    LEFT JOIN LATERAL (
      SELECT p2.name, p2.mobile
      FROM site_contacts sc
      JOIN parties p2 ON p2.id = sc.party_id
      WHERE sc.site_id = l.site_id AND sc.role = 'owner'
      ORDER BY sc.discovered_at ASC NULLS LAST, sc.id ASC
      LIMIT 1
    ) site_owner ON dp_client.id IS NULL AND l.site_id IS NOT NULL
    WHERE COALESCE(l.current_stage, 'calling') NOT IN ('won', 'lost')
      AND (p_owner_ids IS NULL OR l.owner_employee_id = ANY (p_owner_ids))
      -- BDM pool leads stay out of every company figure until assigned
      -- (migration_bdm_handoff.sql) — except for the BDM who brought them in.
      AND (l.owner_employee_id IS NOT NULL OR l.bdm_employee_id IS NULL
           OR (SELECT current_employee_role()) = 'business_development_manager')
  ),
  flagged AS (
    SELECT
      b.*,
      NOT b.is_on_hold AS is_active,
      (COALESCE(b.client_name_direct, b.client_name_via_site) IS NOT NULL
        AND COALESCE(b.client_name_direct, b.client_name_via_site) <> '')   AS f_client_name,
      (COALESCE(b.client_mobile_direct, b.client_mobile_via_site) IS NOT NULL
        AND COALESCE(b.client_mobile_direct, b.client_mobile_via_site) <> '') AS f_client_number,
      (b.site_id IS NOT NULL AND (COALESCE(b.house_no, '') <> '' OR COALESCE(b.locality, '') <> '')) AS f_address,
      (b.site_id IS NOT NULL AND COALESCE(b.pincode, '') <> '')             AS f_pincode,
      (b.site_id IS NOT NULL AND COALESCE(b.site_stage, '') <> '')         AS f_site_stage,
      (b.product_id IS NOT NULL)                                           AS f_product,
      CASE
        WHEN NOT b.is_on_hold THEN NULL
        WHEN p_now IS NULL OR p_tz_offset_minutes IS NULL THEN NULL
        ELSE FLOOR(EXTRACT(EPOCH FROM (
          p_now - ((COALESCE(b.hold_started_at, b.created_at) - make_interval(mins => p_tz_offset_minutes)) AT TIME ZONE 'UTC')
        )) / 86400)::int
      END AS days_on_hold
    FROM base b
  ),
  hold AS (
    SELECT COUNT(*) AS cnt, COALESCE(SUM(value), 0) AS val, AVG(days_on_hold) AS avg_days
    FROM flagged WHERE is_on_hold
  ),
  -- Completeness scopes to every open lead (on-hold included), matching
  -- leads_completeness_detail()'s own scope exactly.
  completeness AS (
    SELECT
      COUNT(*) AS cnt,
      AVG((f_client_name::int + f_client_number::int + f_address::int + f_pincode::int + f_site_stage::int + f_product::int) / 6.0 * 100) AS blended_pct,
      AVG(f_client_name::int)   * 100 AS client_name_pct,
      AVG(f_client_number::int) * 100 AS client_number_pct,
      AVG(f_address::int)       * 100 AS address_pct,
      AVG(f_pincode::int)       * 100 AS pincode_pct,
      AVG(f_site_stage::int)    * 100 AS site_stage_pct,
      AVG(f_product::int)      * 100 AS product_pct
    FROM flagged
  ),
  -- Gap count AND its denominator both come off the same `is_active` rows
  -- in one pass (FILTER, not two separate queries) — this is what used to
  -- be a sixth, standalone `leads` scan (gap_denominator) and no longer is.
  gap AS (
    SELECT
      COUNT(*) FILTER (WHERE is_active AND next_followup_date IS NULL) AS cnt,
      COUNT(*) FILTER (WHERE is_active)                                AS denom
    FROM flagged
  ),
  -- Workload includes on-hold leads (is_open, not is_active) — see this
  -- file's header note on that deliberate, flagged-for-veto choice.
  workload AS (
    SELECT owner_employee_id AS owner_id, owner_label AS owner_name,
           COUNT(*) AS open_lead_count, SUM(value) AS open_pipeline_value
    FROM flagged
    GROUP BY owner_employee_id, owner_label
  ),
  workload_busiest AS (
    SELECT * FROM workload ORDER BY open_lead_count DESC, owner_id ASC LIMIT 1
  ),
  workload_lightest AS (
    SELECT * FROM workload ORDER BY open_lead_count ASC, owner_id ASC LIMIT 1
  ),
  deals AS (
    SELECT id, value,
      ROW_NUMBER() OVER (ORDER BY value DESC, id) AS rn,
      COUNT(*) OVER ()                            AS total_n
    FROM flagged WHERE is_active
  ),
  deal_totals AS (
    SELECT
      COALESCE(MAX(total_n), 0)               AS total_n,
      COALESCE(SUM(value), 0)                 AS total_value,
      GREATEST(1, CEIL(COALESCE(MAX(total_n), 0) * p_top_fraction))::int AS top_n
    FROM deals
  ),
  concentration AS (
    SELECT
      dt.total_n,
      dt.total_value,
      dt.top_n,
      COALESCE((SELECT SUM(d.value) FROM deals d WHERE d.rn <= dt.top_n), 0) AS top_value
    FROM deal_totals dt
  )
  SELECT
    hold.cnt, hold.val, hold.avg_days,

    completeness.cnt, completeness.blended_pct, completeness.client_name_pct,
    completeness.client_number_pct, completeness.address_pct,
    completeness.pincode_pct, completeness.site_stage_pct, completeness.product_pct,

    gap.cnt, gap.denom,
    CASE WHEN gap.denom = 0 THEN 0::numeric
         ELSE ROUND(gap.cnt::numeric / gap.denom * 100, 1) END,

    (SELECT COUNT(*) FROM workload),
    (SELECT owner_id FROM workload_busiest), (SELECT owner_name FROM workload_busiest),
    (SELECT open_lead_count FROM workload_busiest), (SELECT open_pipeline_value FROM workload_busiest),
    (SELECT owner_id FROM workload_lightest), (SELECT owner_name FROM workload_lightest),
    (SELECT open_lead_count FROM workload_lightest), (SELECT open_pipeline_value FROM workload_lightest),

    CASE WHEN concentration.total_value = 0 THEN 0::numeric
         ELSE ROUND(concentration.top_value / concentration.total_value * 100, 1) END,
    concentration.top_n, concentration.total_n, concentration.total_value
  FROM hold, completeness, gap, concentration
$$;


CREATE OR REPLACE FUNCTION leads_category_breakdown(p_owner_ids integer[] DEFAULT NULL)
RETURNS TABLE (
  category_group text,
  category       text,
  lead_count     bigint,
  deal_value     numeric
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  WITH scoped_leads AS (
    SELECT
      l.id,
      COALESCE(l.current_stage, 'calling') AS current_stage,
      l.site_id,
      l.quote_value,
      l.order_value,
      s.site_stage,
      a.area_name,
      p.name AS product_name
    FROM leads l
    LEFT JOIN sites    s ON s.id = l.site_id
    LEFT JOIN areas    a ON a.id = s.area_id
    LEFT JOIN products p ON p.id = l.product_id
    WHERE (p_owner_ids IS NULL OR l.owner_employee_id = ANY (p_owner_ids))
      -- BDM pool leads stay out of every company figure until assigned
      -- (migration_bdm_handoff.sql) — except for the BDM who brought them in.
      AND (l.owner_employee_id IS NOT NULL OR l.bdm_employee_id IS NULL
           OR (SELECT current_employee_role()) = 'business_development_manager')
  ),
  -- Mirrors dealValueFor() exactly: an open lead's value is its quote alone
  -- (order_value is only ever set once a deal is booked — see that file's
  -- own header comment); a won/lost lead prefers order_value, falling back
  -- to quote_value. Both branches coalesce to 0 for the SUM below, matching
  -- dealValueFor()'s own "0 is correct for adding up" rule.
  valued AS (
    SELECT
      *,
      CASE
        WHEN current_stage IN ('won', 'lost') THEN COALESCE(order_value, quote_value, 0)
        ELSE COALESCE(quote_value, 0)
      END AS deal_value
    FROM scoped_leads
  )
  -- areaCategory(): !site_id -> 'No site'; else sites.areas.area_name ?? 'No area set'
  SELECT 'area', CASE WHEN site_id IS NULL THEN 'No site' ELSE COALESCE(area_name, 'No area set') END,
         COUNT(*), SUM(deal_value)
  FROM valued GROUP BY 1, 2

  UNION ALL

  -- siteStageCategory(): !site_id -> 'No site'; else sites.site_stage || 'Not set'
  -- (JS `||` treats '' as falsy too, unlike `??` — NULLIF is what mirrors that)
  SELECT 'site_stage', CASE WHEN site_id IS NULL THEN 'No site' ELSE COALESCE(NULLIF(site_stage, ''), 'Not set') END,
         COUNT(*), SUM(deal_value)
  FROM valued GROUP BY 1, 2

  UNION ALL

  -- productCategory(): products.name ?? 'Not specified'
  SELECT 'product', COALESCE(product_name, 'Not specified'),
         COUNT(*), SUM(deal_value)
  FROM valued GROUP BY 1, 2

  UNION ALL

  -- stageRows: grouped by current_stage (already defaulted to 'calling'
  -- above). Dashboard.jsx zero-fills every LEAD_STAGE_OPTIONS value that
  -- doesn't come back here — this only needs to return stages that actually
  -- have at least one lead.
  SELECT 'stage', current_stage,
         COUNT(*), SUM(deal_value)
  FROM valued GROUP BY 1, 2
$$;


CREATE OR REPLACE FUNCTION leads_needing_attention(
  p_now               timestamptz,
  p_today             date,
  p_tz_offset_minutes integer,
  p_attention_days    integer DEFAULT 14,
  p_stale_days        integer DEFAULT 7,
  p_silent_quote_days integer DEFAULT 5,
  p_pending_rfq_days  integer DEFAULT 3,
  p_history_starts_at date    DEFAULT DATE '2026-09-02'
)
RETURNS TABLE (
  lead_id              integer,
  party                text,
  owner_name           text,
  owner_id             integer,
  current_stage        text,
  quote_value          numeric,
  order_value          numeric,
  last_activity_at     timestamp,
  last_stage_change_at timestamp,
  lead_created_at      timestamp,
  quote_sent_at        date,
  next_followup_date   date,
  estimated_close_date date,
  rfq_raised_at        date,
  is_stale             boolean,
  is_stale_7d          boolean,
  is_silent_quote      boolean,
  is_followup_overdue  boolean,
  is_slipped           boolean,
  is_pending_rfq       boolean
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  WITH last_activity AS (
    -- Mirrors fetchLastActivityPerLead() + Dashboard's client-side reduction
    -- to one row per lead (it keeps the greatest created_at).
    SELECT a.lead_id, MAX(a.created_at) AS last_at
    FROM activities a
    WHERE a.lead_id IS NOT NULL
    GROUP BY a.lead_id
  ),
  last_stage_change AS (
    -- Mirrors src/lib/attention.js's buildLastStageChangeByLead() — the most
    -- recent stage_history row per lead, regardless of what it was to or
    -- from. Deliberately unfiltered by stage: the row that matters here is
    -- whichever came last, which for a resumed lead is the very change that
    -- took it off on_hold.
    SELECT sh.lead_id, MAX(sh.changed_at) AS changed_at
    FROM stage_history sh
    GROUP BY sh.lead_id
  ),
  base AS (
    SELECT
      l.id,
      COALESCE(l.current_stage, 'calling')                          AS stage,
      l.quote_value,
      l.order_value,
      l.owner_employee_id,
      l.created_at,
      l.quote_sent,
      l.quote_sent_at,
      l.rfq_raised,
      l.rfq_raised_at,
      l.next_followup_date,
      l.estimated_close_date,
      -- isImportedLead(): provenance, never date. The marker the legacy
      -- import files stamp and nothing in the app ever writes. A lead
      -- without it is treated as app-created, i.e. never clamped.
      --
      -- THE COALESCE IS LOAD-BEARING — do not remove it. See
      -- migration_needs_attention_rpc.sql's original comment: without it
      -- every app-created lead's `NOT imported` evaluates to NULL, which
      -- silently dropped leads from the followups_overdue and slipped
      -- buckets (lead #320 among them).
      COALESCE(l.external_reference_id LIKE 'legacy-%', false)      AS imported,
      -- partyLabel(): parties.name ?? sites.nickname ?? sites.locality
      -- ?? '(no party)'. LEFT JOINs so an RLS-invisible party degrades to
      -- the same fallback the embedded-null case produces today.
      COALESCE(p.name, s.nickname, s.locality, '(no party)')        AS party_label,
      COALESCE(e.name, 'Unassigned')                                AS owner_label,
      la.last_at,
      lsc.changed_at AS last_stage_change_at
    FROM leads l
    LEFT JOIN parties   p  ON p.id = l.party_id
    LEFT JOIN sites     s  ON s.id = l.site_id
    LEFT JOIN employees e  ON e.id = l.owner_employee_id
    LEFT JOIN last_activity la ON la.lead_id = l.id
    LEFT JOIN last_stage_change lsc ON lsc.lead_id = l.id
    -- isOpen(): every bucket below only ever considers open leads.
    WHERE COALESCE(l.current_stage, 'calling') NOT IN ('won', 'lost')
      -- BDM pool leads stay out of every company figure until assigned
      -- (migration_bdm_handoff.sql) — except for the BDM who brought them in.
      AND (l.owner_employee_id IS NOT NULL OR l.bdm_employee_id IS NULL
           OR (SELECT current_employee_role()) = 'business_development_manager')
  ),
  instants AS (
    SELECT
      b.*,
      -- JS reads a naive timestamp as LOCAL time.
      (b.created_at - make_interval(mins => p_tz_offset_minutes)) AT TIME ZONE 'UTC' AS created_instant,
      (b.last_at    - make_interval(mins => p_tz_offset_minutes)) AT TIME ZONE 'UTC' AS last_instant,
      (b.last_stage_change_at - make_interval(mins => p_tz_offset_minutes)) AT TIME ZONE 'UTC' AS stage_instant,
      -- JS reads a date-only string as UTC midnight.
      (b.quote_sent_at::timestamp) AT TIME ZONE 'UTC'                                AS quote_instant,
      (b.rfq_raised_at::timestamp) AT TIME ZONE 'UTC'                                AS rfq_instant,
      -- HISTORY_STARTS_AT is built in JS as new Date('<date>T00:00:00') —
      -- no zone suffix, so LOCAL midnight, not UTC midnight.
      (p_history_starts_at - make_interval(mins => p_tz_offset_minutes)) AT TIME ZONE 'UTC' AS history_floor
    FROM base b
  ),
  gated AS (
    SELECT
      i.*,
      -- queueAge()/staleSinceTouch(): the touch reference the stale gates
      -- test, GREATEST(last activity, last stage change) — a stage change
      -- is as real a touch as a logged activity (see
      -- migration_needs_attention_hold_exclusion.sql). GREATEST ignores NULL
      -- arguments and only returns NULL if every argument is NULL, matching
      -- laterOf(...) ?? createdAt exactly. Shared by BOTH is_stale and the
      -- new is_stale_7d below — only the threshold they compare it against
      -- differs.
      FLOOR(EXTRACT(EPOCH FROM (p_now - CASE
        WHEN i.imported AND GREATEST(i.last_instant, i.stage_instant, i.created_instant) < i.history_floor
          THEN i.history_floor
        ELSE GREATEST(i.last_instant, i.stage_instant, i.created_instant)
      END)) / 86400)::int AS touch_gate,
      FLOOR(EXTRACT(EPOCH FROM (p_now - CASE
        WHEN i.imported AND i.quote_instant < i.history_floor THEN i.history_floor
        ELSE i.quote_instant
      END)) / 86400)::int AS quote_gate,
      FLOOR(EXTRACT(EPOCH FROM (p_now - CASE
        WHEN i.imported AND i.rfq_instant < i.history_floor THEN i.history_floor
        ELSE i.rfq_instant
      END)) / 86400)::int AS rfq_gate,
      -- inheritedGraceIsOver(): an inherited promised date gets one standard
      -- ATTENTION_DAYS runway before it counts against anyone. Dates set
      -- inside this CRM are unaffected and fire immediately. Deliberately
      -- still keyed on p_attention_days, not p_stale_days — this grace
      -- period is about the followups_overdue/slipped buckets, unrelated to
      -- the new stale-tile flag.
      (FLOOR(EXTRACT(EPOCH FROM (p_now - i.history_floor)) / 86400)::int >= p_attention_days) AS grace_over
    FROM instants i
  ),
  flagged AS (
    SELECT
      g.*,
      (
        -- A lead currently on hold is excluded from "stale" outright,
        -- however long the pause has run — see
        -- migration_needs_attention_hold_exclusion.sql.
        g.stage <> 'on_hold'
        AND g.touch_gate IS NOT NULL
        AND g.touch_gate >= p_attention_days
      ) AS f_stale,
      (
        -- Same rule, earlier threshold — see this file's own header. Always
        -- true whenever f_stale is (touch_gate >= 14 implies touch_gate >=
        -- 7), so this is a strict superset; it exists as its own flag so JS
        -- can tell "just gone quiet" apart from "in the Needs Attention
        -- queue" instead of only ever seeing the later number.
        g.stage <> 'on_hold'
        AND g.touch_gate IS NOT NULL
        AND g.touch_gate >= p_stale_days
      ) AS f_stale_7d,
      (
        g.quote_sent IS TRUE
        AND g.quote_sent_at IS NOT NULL
        AND g.quote_gate IS NOT NULL
        AND g.quote_gate >= p_silent_quote_days
        -- touchedSinceQuote: last activity strictly after the quote date.
        AND NOT (g.last_instant IS NOT NULL AND g.last_instant > g.quote_instant)
      ) AS f_silent_quote,
      (
        g.next_followup_date IS NOT NULL
        AND g.next_followup_date < p_today
        AND (NOT g.imported OR g.next_followup_date >= p_history_starts_at OR g.grace_over)
      ) AS f_followup_overdue,
      (
        g.estimated_close_date IS NOT NULL
        AND g.estimated_close_date < p_today
        AND (NOT g.imported OR g.estimated_close_date >= p_history_starts_at OR g.grace_over)
      ) AS f_slipped,
      (
        g.rfq_raised IS TRUE
        AND g.quote_sent IS DISTINCT FROM TRUE
        AND g.rfq_raised_at IS NOT NULL
        AND g.rfq_gate IS NOT NULL
        AND g.rfq_gate >= p_pending_rfq_days
      ) AS f_pending_rfq
    FROM gated g
  )
  SELECT
    f.id, f.party_label, f.owner_label, f.owner_employee_id, f.stage,
    f.quote_value, f.order_value,
    f.last_at, f.last_stage_change_at, f.created_at,
    f.quote_sent_at, f.next_followup_date, f.estimated_close_date, f.rfq_raised_at,
    f.f_stale, f.f_stale_7d, f.f_silent_quote, f.f_followup_overdue, f.f_slipped, f.f_pending_rfq
  FROM flagged f
  -- WIDENED: OR f.f_stale_7d is new, and is the reason this migration exists
  -- at all — see this file's header. f.f_stale is a subset of f.f_stale_7d
  -- and is kept in the list only for readability; removing it would change
  -- nothing.
  WHERE f.f_stale OR f.f_stale_7d OR f.f_silent_quote OR f.f_followup_overdue OR f.f_slipped OR f.f_pending_rfq
  -- ORDER BY id is REQUIRED, not cosmetic — see migration_needs_attention_rpc.sql.
  ORDER BY f.id
$$;


NOTIFY pgrst, 'reload schema';

COMMIT;


-- ============================================================
-- VERIFY (read-only — run after, in the SQL Editor)
--
-- 1. The new kind is allowed:
--   SELECT pg_get_constraintdef(oid) FROM pg_constraint
--    WHERE conname = 'notifications_kind_check';
--   Expect 'bdm_pool_nudge' in the list.
--
-- 2. All eight functions carry the pool rule and are still SECURITY INVOKER:
--   SELECT proname, prosecdef,
--          pg_get_functiondef(oid) LIKE '%bdm_employee_id IS NULL%' AS has_pool_rule
--     FROM pg_proc
--    WHERE proname IN ('leads_on_hold_detail','leads_completeness_detail',
--                      'leads_followup_gap_detail','leads_workload_by_owner',
--                      'leads_open_deal_ranking','dashboard_snapshot_metrics',
--                      'leads_category_breakdown','leads_needing_attention');
--   Expect 8 rows, prosecdef = false and has_pool_rule = true on every one.
--   (More than 8 rows means an old overload is still lying around — tell
--   Claude before going further.)
--
-- The behavioural check (a pool lead missing from the owner's figures but
-- present on the pool card) is done in the app as a real owner session —
-- never here, where BYPASSRLS and no auth.uid() make every role look alike.
-- ============================================================
